let fila = ["Sofia", "David", "Juan"];
console.log("Parte #1");
console.log(fila);
fila.push("Sara");
fila.push("Augustin");
fila.shift();
console.log("Parte #2");
console.log(fila);
fila.splice(1,0, "Renata");
fila.push("Elena");
console.log("Parte #3");
console.log(fila);
